### ISSUE TITLE
Need for change in mandatory parameters suggested in DOPE statement

### ISSUE THREAD

**Issue by EvilDoof** [seanfroste/vscode-spectra-assist#6]
Current autocomplete for the DOPE statement suggests XMIN XMAX YMIN YMAX as mandatory parameters. However, this is not the case when using a MASK statement in conjunction with DOPE, where the box defined by XMIN XMAX YMIN YMAX can be skipped.

CM on the other hand is a mandatory parameter which defines the maximum concentration. This must be used in all cases and can be included

![Screenshot 2024-04-18 131150](https://github.com/seanfroste/vscode-spectra-assist/assets/45903569/4d644e6a-13b7-4ff7-8901-ee9a0f3647b8)

**Comment by seanfroste** [comment]
#### Proposed Fix
- Omit the box params (`X/Y/ZMIN` `X/Y/ZMAX`) altogether in the snippet
- Include `CMAX` as a mandatory param for both variants of the `DOPE` statement snippet (`TYPE` and `ELEMENT`)

(just to be clear, the manual `CMAX` as an optional param)

does this sound good? @EvilDoof

**Comment by EvilDoof** [comment]
Yes, for all practical applications CMAX is necessary. Though there might be certain niche instances where it might not be necessary

**Comment by seanfroste** [comment]
Better leave it out then, right? Since the CMAX param has a snippet to add it in on your own anyway
